services:
  web:
    build:
      context: .
      dockerfile: Kasta.Web/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./config.xml:/config.xml
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: changeme123
      POSTGRES_USER: kasta
      POSTGRES_DB: kasta
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - local_pgdata:/var/lib/postgresql/data
volumes:
  local_pgdata:
