services:
  web:
    image: ghcr.io/ktwrd/kasta:latest
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./kasta-config:/config
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: changeme123
      POSTGRES_USER: kasta
      POSTGRES_DB: kasta
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - local_pgdata:/var/lib/postgresql/data
volumes:
  local_pgdata:
