name: Build Application

on:
  push:
    branches: [ main ]
    tags: "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: dotnet build Kasta.Web --no-incremental --nologo --configuration Release

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'ref/heads/main' || startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        runtime:
          - "win-x64"
          - "win-arm64"
          - "linux-x64"
          - "linux-arm"
          - "linux-arm64"
          - "linux-musl-x64"
          - "linux-musl-arm"
          - "linux-musl-arm64"
          - "osx-x64"
          - "osx-arm64"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Build ${{ matrix.runtime }}
        run: dotnet publish Kasta.Web --configuration Release -p:PublishSingleFile=true -p:ReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true -p:CopyOutputSymbolsToPublishDirectory=false --self-contained --runtime ${{ matrix.runtime }} --output dist
      
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: Kasta.Web-${{matrix.runtime}}
          path: dist/${{ matrix.runtime }}

  docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Environment Variables
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "CONTAINER_VERSION=$(git describe --tags --abbrev=0).$([[ $GITHUB_REF = refs/tags/* ]] && echo 0 || echo 65534)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date --iso-8601=s)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish DEV Image
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: Dockerfile
          push: true
          tags: |
            ktwrd/kasta:dev
            ktwrd/kasta:dev-${{ env.CONTAINER_VERSION }}
            ghcr.io/ktwrd/kasta:dev
            ghcr.io/ktwrd/kasta:dev-${{ env.CONTAINER_VERSION }}

      - name: Build & Publish LATEST Image
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: Dockerfile
          push: true
          tags: |
            ktwrd/kasta:latest
            ktwrd/kasta:dev
            ktwrd/kasta:${{ env.CONTAINER_VERSION }}
            ktwrd/kasta:${{ env.TAG }}
            ghcr.io/ktwrd/kasta:latest
            ghcr.io/ktwrd/kasta:dev
            ghcr.io/ktwrd/kasta:${{ env.CONTAINER_VERSION }}
            ghcr.io/ktwrd/kasta:${{ env.TAG }}

      